default: vm

vm:
	gsc -exe src/utils.scm \
		 src/version.scm \
		 src/error.scm \
		 src/globals.scm \
		 src/env.scm \
		 src/values.scm \
		 src/lambda.scm \
		 src/reader.scm \
		 src/printer.scm \
		 src/kernel.scm \
		 src/shell.scm \
		 src/compiler.scm \
		 src/bardvm.scm

clean:
	rm -f src/bardvm
