#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/asciidoctor.css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="./css/styles.css" />
#+OPTIONS: toc:nil
#+OPTIONS: num:1
#+OPTIONS: ^:nil
#+TITLE: README

Bard is a small, high-level, general-purpose programming lnaguage.

It's interactive, dynamic, and impreuly functional. It's designed to support changing a program interactively while it runs.

It provides support for concurrent and distributed programs, and encourages the use of immutable data.

The current work-in-progress version is 0.7. Its code is in an intermediate state of conversion from the Bard 0.3 implementation to simplify the surface language and support new language and runtime features.

The file docs/bard7.adoc is a work in progress that documents the intended Bard 0.7 language. The implementation doesn't match it yet, and the document itself is not yet done.

The directory ~vm~ contains work in progress on the bard vm.

The directory ~compiler~ contains work on the compiler.


For a description of the Bard 0.7 language, see docs/bard7.adoc.
