(response-content-type "text/html")
;;Not a valid processing-instruction, technically.
;;#<?xml version='1.0'?>
(unescaped-data "<?xml version='1.0'?>\n")
#<!--This is generated by HelloCgiS-->
#<body>
  &(make-element 'p (format "The request URI was: ~a" (request-uri)))
  <p>&(let ((query (request-query-string)))
        (if query
            (format "The query string was: ~a" query)
	    "There was no query string."))</p>
</body>

