default: vm

vm:
	csc -exe src/utils.scm \
		src/version.scm \
		src/error.scm \
		src/globals.scm \
		src/env.scm \
		src/values.scm \
		src/lambda.scm \
		src/reader.scm \
		src/printer.scm \
		src/kernel.scm \
		src/shell.scm \
		src/quasiquote.scm \
		src/compiler-let.scm \
		src/compiler-set!.scm \
		src/compiler-define.scm \
		src/compiler.scm \
		src/macros.scm \
		src/repl.scm \
		src/bardvm.scm

clean:
	rm -f src/bardvm
