= bard 0.7
mikel evins
:toc: preamble
:toclevels: 2

bard 0.7 is the seventh major iteration of design and implementation of the Bard programming language.

Bard is intended to be an old-fashioned Lisp in the sense that it fully embraces interactive programming and unrestricted malleability. This version of the implementation also shoots for the kind of easy portability of source and object code represented by old-fashioned Smalltalk environments, using a compiler to a platform-agnostic bytecode format and a portable virtual machine.

Bard 0.7 also embraces more recent developments in programming-language design, including a functional-first language with immutable-first datatypes, protocol-oriented programming, and support for internet protocols and widely-used data formats.

Finally, Bard is intended to be a small language with a relatively simple surface.

This document records my progress toward these goals.

== Data

Bard 0.7 offers the following built-in basic datatypes:

[cols=".<1m,.^3m,.>3",options="header",]
|===
|Type name |Examples                                 |Description
|Anything  | 1, true, "hello"                        |Every possible value.
|Undefined |undefined                                |No useful value.
|Null      |nothing                                  |The empty collection.
|Boolean   |true, false                              |True and false. `nothing` is also logically false.
|Number    |0, 1, -2, 3/4, 5.6                       |Any numeric value.
|Text      | "", "Some text"                         |Text strings.
|List      |[1 2 3]                                  |A sequence of values.
|          |(+ 1 2 3)                                |Written this way, a List is treated as a function call
|Map       |{:name "Fred" :color "Orange"}           |A mapping from keys to values.
|Function  |(function foo Bar -> Baz)                |A polymorphic operator
|Method    |(^ [x] (+ x 1))                          |A monomorphic operator
|Structure |(record <point> {:x <float> :y <float>}) |A blueprint for constructing values.
|          |(tuple <ostype> [<byte> {:exactly 4}])   |
|          |(enum <primary-color> 'Red 'Green 'Blue) |
|===

== Types

A Bard *type* is either a *structure* or a *class*. *Structures* are concrete blueprints for constructing values. *Classes* are named collections of types.

A *structure* describes the structure of a family of values and the data that populate them. Bard defines a set of *built-in structures*, including concrete representations of all the types listed in the previous section. It also defines a set of *operators* that you can use to define your own structures.

A structure can be *instantiated*–that is, it can be used to create values. Values created from a structure are said to be *instances* of that structure, and they belong to the *type* that the structure represents.

A *class* is an abstract type, a name for a collection of other types.  It does not specify any internal structure or any taxonomic relationship to any other type. A class might be *empty*, with no members and no instances.

Most classes are defined to fulfill one or more roles in a *protocol*.

A *protocol* is a named set of *operators* and *variables*.  Operators accept input values and produce output values. A protocol can declare classes for those inputs and outputs. Until other types are made members of those classes, the classes are empty.

The most common way to make a type into an member of a class is by *specializing* a protocol function. If a function has a method that is specialized for a type on some parameter, then that type becomes a member of that parameter's class.

For example, suppose I define a function like this:

....
(function foo Bar -> Baz)
....

`foo` is now a function that takes one argument of type `Bar` and returns one value of type `Baz`. `Bar` and `Baz` are now classes. If these names were never used before in another function or class definition then they are empty–they have no members and no instances.

I can make the structure `<small-integer>` into a member of the class `Bar` by writing a method that specializes `foo` on it:

....
(define method (foo bar)
  with {bar <small-integer>}
  ...)
....

The `with` clause applies a *constraint* to the argument `bar`: its value must be an instance of `<small-integer>`.

To be more precise: `<small-integer>` is the constraint that `bar` must satisfy. If the constraint is a type, then the value of `bar` must be an instance of that type in order for this method to match the function call. Other constraints are also possible. For example, the constraint `(exactly 101)` means that `bar` has to be equal to 101, and the integer 101 (and only the integer 101) becomes a member of the `Bar` class.

`<small-integer>` is now a member of the `Bar` class. If I call `foo` with an instance of `<small-integer>`, like so:

....
(foo 15)
....

then Bard finds my method and applies it.

== Operators

An *operator* is a value that can be applied to some sequence of expressions to compute a result. There are four kinds of operators:

* *special forms* are built into the Bard system. Each special form can follow its own rules of evaluation.
* *functions* are polymorphic operators that evaluate their arguments, examine the results, and choose a *method* to apply according to the matching rules given by `define method` forms.
* *methods* are monomorphic operators that apply bard expressions to their input parameters to compute results. Methods are commonly applied by functions, but may also be referenced and applied directly.
* *macros* are rewrite rules. When you call a macro, the rule given by the macro's definition rewrites the call into a new expression and then evaluates that. Macros are generally used to add new syntax to Bard.

== The Bard Runtime

Bard 0.7 is a virtual machine that executes portable bytecode. It supports compiling Bard source code in the form of S-expressions to a bytecode format called *bardo*.

I plan to eventually support compiling bardo to native code, and to support execution of both bytecode and native code in the same runtime.

== Lexical Syntax

Bard's lexical syntax provides ways to write literal values of most of its built-in datatypes. For example:

[cols="1m,1m,4",options="header",]
|===
|Syntax    | Class |Description
|nothing   | Null  |The empty collection
|3.1415926 | Float |A floating-point number
|[1 2 3]   | List  |A list of integers
|===

The table gives the *class* of each value, but not the *structure*. When you write the lexical syntax for a value, Bard constructs and returns an instance of the *default structure* for that type. For example, the default structure for the `List` type is `<cons>`, so writing `[1 2 3]` returns a `<cons>`.

What if you want a different structure? You can write:

....
#:<vector> '(1 2 3)
....

which tells Bard you want it to return a `vector` instead. The syntax `#:<vector>` is shorthand for

....
(as <vector> [1 2 3])
....

Bard may rewrite this expression as a direct call to the `vector` constructor:

....
(vector 1 2 3)
....

Alternatively, you can of course also call the constructor yourself.

When you write a literal value, Bard constructs an instance of the default structure for the expression's class. If you want to ensure that the value belongs to some specific structure, then you must say so explicitly, as in the example above.

=== Named Constants

*Named constants* are *names* that are defined in all lexical contexts, and that always refer to the same value. Four of them are defined by the Bard language:

[cols="m,",options="header",]
|===
|Name      |Description
|nothing   |The empty list, set, or map.
|true      |The Boolean true value.
|false     |The Boolean false value.
|undefined |The absence of any useful value
|===

=== Numbers

*Numbers* are numeric values including integers, ratios, and decimal numbers. Bard 0.7 defines several built in numeric structures.

[cols="m,m,",options="header",]
|===
|Values     |Structure       |Notes
|0, 100, -2 |<small-integer> |Integers that can be conveniently represented by a machine word
|9999999999999999999 |<big-integer> |Unlimited-precision integers
|2/3 |<ratio> |Fractional number represented by ratios of integers
|0.1 |<float> |Decimal numbers represented as floating-point values
|===

=== Names

*Names* are values that Bard uses to label elements of the language like functions, variables, and special forms, or to represent certain kinds of name-like data, such as files and network resources. There are three kinds of names:

[cols="1,1m,1m,4",options="header",]
|===
|Kind |Examples |Structure |Notes
|Symbol|foo, Bar, <symbol> |<symbol> |Names used for variables, functions, and so on
|Keyword|:type, :Family |<keyword> |Names that always evaluate to themselves
|URI|@"file:///tmp/",@"https://barcode.net" |<uri> |Universal Resource Identifiers and URLs
|===

=== Lists

Lists are sequences of values that are addressable by index. `List` is a class, not a structure, and its members include several different structures that represent sequences of values. The `Listing` protocol provides numerous operators that work on Lists.

Some List structures are mutable; others are immutable.

[cols="m,",options="header",]
|===
|Examples  |Notes
|[1 2 3]  | A List of integers
|[[1 2 3]["one" "two" "three"]]  | A List of Lists
|"A list of Characters"  | Text strings are also Lists (see "Text Strings," below)
|===

Bard normally prints a list using parentheses rather than square brackets. We can see this when we enter lists at the Bard prompt:

....
> [1 2 3]
(1 2 3)
....

Both ways of writing Lists are correct; the difference between then is that when Bard reads a List written in parentheses, it interprets it as a function call.

....
> (1 2 3)
ERROR: 1 is not an operator!
....

You can tell Bard not to evaluate a List in parentheses using a *quote*:

....
> '(1 2 3)
(1 2 3)
....

...or you can use square brackets as a shorthand for the List constructor.

....
[1 2 3]
....

means the same thing as

....
(list 1 2 3)
....


=== Text Strings

Text strings, like `"Hello"`, are Lists of Characters. All of the operators of the `Listing` protocol work on them, but they also participate in the `TextProcessing` protocol, which adds many operators specialized for handling text.

Note that this does not mean that strings are implemented inefficiently as singly-linked-lists or some such data structure. Remember that `Text` and `List` are classes, not structures. Saying that a text string is a list of characters simply means that the structure that represents it supports the `Listing` protocol; it doesn't specify anything about its representation.

Like `List`, `Text` is a class, not a structure, and there may be several different structures that implement it.

=== Characters

Characters are the atomic elements of text strings. The class `Character` comprises the structures used to represent them.

[cols="1m,3",options="header",]
|===
|Examples  |Notes
|#\A, #\z, #\space  |Bard supports several different `Character` structures
|===

=== Maps

Maps are data structures that associate *keys* with *values*. The `Map` class comprises several such structures with different storage and performance characteristics.

Some maps are mutable; others are immutable.

[cols="2m,3",options="header",]
|===
|Examples |Notes
|{}, {:name "Fred" :age 35} |Bard supports several
mutable and immutable types of maps
|===

=== Functions

Functions are polymorphic operators examine their inputs, match them to methods, and apply the methods to the inputs.

Following is an expression that creates a named function:

....
(function foo Bar -> Baz)
....

Besides saying that `foo` is a function, this expression also says that `Bar` and `Baz` are classes whose members can be inputs and outputs of `foo`.

Defining a function doesn't say how it works or what values is accepts or produces. It only defines some abstract function and classes that may be given concrete meaning by *specializing* the function.

*Specializing* a function means defining a *method* that applies to some concrete set of input values. The next section describes specialization in more detail.

=== Methods

The special form named `^` ("caret" or "lambda") constructs a *method*, also known as a *monomorphic function*. A method is a procedure that can be applied to some sequence of values to compute a result. Unlike functions, methods do not examine their inputs before choosing the code to apply to them. A method simply applies its body to its arguments.

Following is an expression that creates a method:

....
(^ [x] (* x x))
....

This nameless method accepts one parameter, called `x`, and multiples it by itself.

Although you can construct methods this way and use them directly, the most common way to create and use them is by using the special form `define method` to *specialize* a function:

....
(define method (add x y)
  with {x <small-integer> y <small-integer>}
  (+ x y))
....

This example *specializes* the function `add`, meaning that it specifies a set of input parameters and a method that applies to them. This definition says that `add` accepts two arguments, and they must be nstances of the structure `<small-integer>`. If we pass arguments of any other number or type then this method is not applied.

`define method` creates a method and adds it to the named function--creating the function as well, if it doesn't already exist. It also adds the rule that defines the requirements that the arguments must meet in order for the method to apply to them. 

We can add another method to the same function, matching a different structure:

....
(define method (add x y)
  with {x <string> y <string>}
  (cat x y))
....

The `<small-integer>` version of `add` uses the addition operator on its arguments, and the `<string>` version instead uses `cat`, which concatenates the strings.

We can add more methods, matching any structures we like in any combination. The defined methods will be called when we pass parameters of the required types.

We can also specify other matching rules. For example, the following method matches only when the parameters are exactly 4 and 2:

....
(define method (add x y)
  with {x (exactly 4)
        y (exactly 2)}
  (print "You have discovered the answer to life, the universe, and everything: 42!"))
....

The `with` clause defines the matching rule for the parameters. If it's a map, as in these examples, then the keys are parameter names and the values are tests that the parameters must satisfy. If the tests are just types, then the rule is satisfied when the value passed for each parameter belongs to the corresponding type.

`(exactly x)` is a test that returns true when a parameter is equal to `x`.

Other matching rules are also supported.

== Naming Conventions

Bard uses some naming conventions that are not strictly enforced by the compiler, but which are strongly encouraged for the sake of clarity.

=== Constants

Constants are read-only variables. By convention, their names start and end with `+`.

....
+Pi+
+C+
+fine-structure-constant+
....

*Constants* are read-only variables.

=== Special Variables

*Special variable* are global variables--more or less. By convention, their names start and end with `*`.

....
*window*
*process-id*
*epoch*
....

=== Protocols

A *protocol* is named collection of related operators and variables. You can think of a protocol as a set of tools for carrying out some activity. The convention is to choose a name that describes the activity, and to capitalize the name: `*Listing*`, for example, or `*Ordering*`.

....
Listing
Mapping
Streaming
....

=== Classes

A *class* is a named collection of *types*. Types, remember, may be either structures or classes, so classes may be members of other classes.

The convention is to name a class with a capitalized noun. The noun should reflect the role the type is intended to fill.

....
List
Map
Stream
....

=== Structures

A *structure* is a concrete description of how values are combined to form a new type of value. Structures may be directly instantiated by allocating space to hold their constituent values and filling in the space with data. Classes can't be instantiated in this way. Because a class is just a name for a set of other types, it can be instantiated only indirectly. The only way to make an instance of a class is to make an instance of one of it member structures.

For structures, the convention is to name them with nouns that describe their concrete representations, spell the nouns in lower case, and enclose the name in angle brackets ("<>").

....
<character>
<cons>
<null>
<small-integer>
....

=== Predicates

*Predicates* are operators of one argument that return true or false.

The convention is to end the names of predicates with question marks ("?").

....
empty?
even?
number?
....

=== Accessors

An *accessor* is an operator that returns the value of a field in a value. If a slot is *mutable* then the accessor may also be used with the `set!` special form to replace the value.

The convention is to start the name of an accessor with a dot (".").

....
.active?
.name
.width
....

=== Mutators

A *mutator* is an operator that destructively modifies the value in a slot, replacing the old value with a new one, or that destructively rearranges the data in an object (for example, a sort that rearranges the the contents of an array in-place).

The convention is to end the names of mutators with exclamation points ("!").

....
replace!
reverse!
set!
.set-name!
....

== Structures

There are three kinds of structures:

- *records* are structures made of named slots.
- *tuples* are structures made of sequences of elements identified by indexes.
- *enumerations* are structures defined as one or more named values, optionally with one or more data parameters associated with the names.

This section describes how to define and instantiate structures, and how to operate on them.

=== Records

=== Tuples

=== Enumerations

== Protocols

Protocols define collections of related operators and variables designed to support particular activities. Examples of Bard protocols include `Comparing`, `Converting`, `Creating`, `Listing`, `Mapping`, `Printing`, `TextProcessing`, and so on.

Most Protocols are named with the suffix `-ing`, but not all are. `Macros` and `System` are two protocols that break this stylistic rule.

This section describes how to define and use protocols.

== Operators

Operators are values that tell Bard to eecute computations when they appear in the first position of a `List` expression written with parentheses. Such expressions are called *operations*.

There are four different kinds of operations, each with a different purpose and a different evaluation rule.

=== Special Forms

User cannot define special forms.

=== Functions

=== Methods

=== Macros

== Operations

An *operation* is an expression that calls an *operator*.

For example:

....
(+ 2 3 4)

(bind [(x 1)
       (y 2)]
 (* x y))

(set! (.x pt) 100)
....

Bard expresses operations as Lists whose first elements are operators, and whose remaining elements are the operators' arguments. Argument expressions may themselves be operations.

Different types of operators have different rules of evaluation for argument expressions. *Functions* and *methods* evaluate argument expressions before passing them to the operator.

A *macro* expression passes the whole expression to the rule given by the macro's definition; that rule rewrites the expression before it's evaluated, and the rule determines whether and how the arguments are evaluated.

*Special forms* are built into the Bard runtime, and each one has its own rules of evaluation.

For example:

....
(def x (+ 2 3))
....

`def` defines a special variable. It evaluates its second argument, but not its first. The above example creates a special variable named `x` whose initial value is `5`.

....
(if nothing
  (/ 1 0)
  (print "No worries!"))
....

`if` evaluates its first argument. If the value is true then it evaluates its second argument; if not, it evaluates its third argument. In the above example, if `nothing` were true then the expression would signal a divide-by-zero error. Because it's not, it instead prints "No worries!". The division by zero is never evaluated.


== Variables

As we saw in the previous section, the special form `def` defines *special variables*:

....
(def x (+ 2 3))
....

This example creates a *special variable* named `x` and gives it the value `5`.

A *special variable* is a name that stands for a value. Any Bard code in a program can get and set that value of a special variable.

=== Definitions

`def`
`define`


=== Lexical variables

It's generally not a good practice to make variables accessible everywhere. The more places a variable is referenced, the more places its value might be changed, and the more places you have to check when keeping track of the code that reads and writes it.

A *lexical variable* is a variable that is accessible only in a certain bounded body of code, called its *lexical environment*. Most variables should be lexical rather than special variables, because they're easier and safer to manage that way.

Bard offers several ways of creating lexical variables. The two most basic are the `bind` special form and *parameter bindings*.

=== The `bind` special form

The `bind` special form creates lexical variables. For example:

....
> (bind [(x 2)]
    (+ x 1))
3
....

In this example, `bind` creates a lexical variable named `x` and binds it to `2`. The body of the `bind` form then refers to that variable in the expression `(+ x 1)`, returning the sum.

`bind` can create more than one variable:

....
> (bind [(x 2)
         (y (+ x 1))]
    (+ x y))
5
....

Variables that appear later in the sequence of bindings can refer to those that appear earlier, as this example shows.

=== Parameter bindings

*Parameter bindings* are created when an operation is called with arguments.

Consider a simple method that returns the greater of two numbers:

....
(^ [x y] (max x y))
....

This method creates the lexical variables `x` and `y`. In the body of the method, `x` and `y` take on the values of the two arguments passed to the method.

Let's capture the method in a special variable and call it:

....
> (def bigger (^ [x y] (max x y)))
(^ [x y] (max x y))
> (bigger 2 3)
3
....

When we apply `bigger` to 2 and 3, `x` is bound to the value `2` and `y` is bound to the value `3`. The method evaluates its body with the variables bound to those values and returns the greater number.

== Returning multiple values

The special form `values` returns multiple values:

....
> (values 1 2 3)
1
2
3
....

The `bind` special form can bind variables to the multiple values returned by `values`:

....
> (bind [(x y z (values 1 2 3))]
    (* x y z))
6
....

If there are more variables than returned values, then the variables are bound to the returned values in order, and the extra variables are bound to `nothing`. If there are more values than variables, the extra values are ignored.

== Packages

Named objects in Bard are named by *symbols*. Symbols exist in *packages*. A *package* is a namespace containing a collection of symbols. 

A *fully-qualified symbol* is a symbol written with the name of the package that it belongs to, for example:

....
bard.core:bind
bard.core:define
bard.user:foo
....

=== Keywords

A special case is the `bard.keyword` package. In a fully-qualified name, the name of the `bard.keyword` package may be omitted.

In other words, writing

....
:foo
....

is exactly the same as writing

....
bard.keyword:foo
....

Symbols in the `bard.keyword` package are treateed specially: they always evaluate to themselves.

=== `\*package*`

Bard defines a special variable, `bard.core:*package*`, whose value is the *current package*. The *current package* is the package used to look up symbols whose names are not fully qualified.

For example, if `\*package*` is currently the package named `bard.core`, then `bind` is automatically interpreted to mean `bard.core:bind`.

Bard defines a `Packaging` protocol that provides a set of operators and variables for working with packages.


== Assignment

== Flow of Control

== Conditions

== Built-in Protocols

=== Addressing

Operations on resource names and identifiers.

=== Comparing

Testing values for equality, equivalence, and sort order.

=== Converting

Constructing values of one type that are in some sense equivalent to values of another type. Alternatively, copying values from one type to another.

=== Creating

Constructing values from structures.

=== Listing

Operations on sequences of values.

=== Macros

Macros defined by Bard.

=== Mapping

Operations on mappings from keys to values.

=== Packaging

Operations on packages (namespaces).

=== Pairing

Operations on paired values.

=== Printing

Printing output.

=== Reading

Reading input.

=== Serializing

Converting values to a form that can be transported and stored outside the bard runtime, and converting values in such forms back into live Bard data in the runtime.

=== Streaming

Operations on objects that produce or consume values.

=== System

Tools for configuring, maintaining, and controlling Bard itself.

=== Tapping

Operations that convert values to streams.

=== TextProcessing

Operations on text strings.

=== Typing

Operations on types and operations on values that produce types.
