= bard 0.7

== Named Constants

`undefined`:: No useful value
`nothing`:: An empty list, map, or stream
`true`:: The Boolean true value
`false`:: The Boolean false value

== Special Forms

[horizontal]
`apply`:: Call a procedure with a list of parameters
`begin`:: Evaluate a sequence of expressions and return the value of the last
`bound?`:: Test whether a *variable* or *slot* has a value
`const`:: Define an *immutable global variable*
`def`:: Define a *mutable global variable*
`define`:: Define one of several global constructs, including classes, functions, and macros
`if`:: Choose which of two expressions to evaluate
`let`:: Define a set of *immutable lexical variables*
`method`:: Create a *monomorphic* procedure
`quote`:: Ask Bard not to evaluate an expression, but instead to return it unchanged
`set!`:: Update the value of a *mutable variable*
`setter`:: Return a procedure that can update a *variable* or *slot*
`unwind-protect`:: Create a control structure that can guarantee that an *exit expression* is evaluated, no matter how control leaves the structure
`values`:: Return zero or more values
`var`:: Define a set of *mutable lexical variables*
`with-exit`:: Create a control structure that defines an *exit procedure* within the structure

== Core Functions

[horizontal]
`initialize`:: A function automatically called by Bard that sets up the initial state of a newly-constructed value
`make`:: A function that allocates a new Bard value


== Built-in Protocols

[horizontal]
`Comparing`:: Operations that compare identity, equivalence, or sort order
`Conditions`:: Values and operations that represent and handle exceptional occurrences
`Constructing`:: `make`, `initialize`, and other procedures and variables used in creating values
`Converting`:: `as` and other procedures and variables used to construct values of one type from values of another
`Control`:: Extended control structures
`Functions`:: Operations on functions and methods
`Lists`:: Creating and operating on ordered sequences of values
`Macro`:: Defining and using *macros*, and several built-in macros
`Maps`:: Creating and operating on finite maps from keys to values
`Math`:: Numbers and mathematical operations
`Messaging`:: Communication between local and remote Bard processes
`Names`:: Creating and operating on *names* including *symbols*, *keywords*, and *uris*
`Network`:: Creating and operating on network connections
`Processes`:: Creating and operating on local and remote Bard processes
`Streams`:: Creating and operating on objects that produce or consume sequences of values
`System`:: Operations on the Bard runtime system
`Taps`:: Operations that create streams from procedures and values
`Text`:: Creating and operating on text strings and text characters
`Types`:: Operations on types

== Syntax

=== Lexical Notation

[horizontal]
`[...]`:: Brackets delimit lists. Expressions between the brackets are the elements of the list.
`(...)`:: Brackets delimit *operations*. An *operation* is a list that denotes a procedure call.
`{...}`:: Braces delimit maps. Expressions between the braces are the alternating keys and values of the map.
`Foo`:: A sequence of alphanumeric characters that does note denote a number is a *symbol*. Bard uses symbols to sstand for variables, procedure names, types, and other names in Bard exressions.
`Bar:`:: A symbol that ends in a colon (':') is a *keyword*. A keyword is a constant that always stands for itself. Common uses of keywords are as keys in maps, or to label arguments in functions.
`1.23`:: Bard provides convenient syntax for several types of numbers, including integers, ratios, and floating-point numbers.
`"A text string"`:: Double quotes delimit text strings.
`#\A`:: 'Hash-sign-backslash' denotes a text character. The intended character is denoted by a name. In the case of printable characters, the name of the character is the character itself.
`#U+0020`:: 'Hash-sign-U-+' denotes a text character. The character is given in standard Unicode hexadecimal notation.
`;`:: A semicolon denotes the start of a line comment. Bard ignores comments. A line comment ends at the next line break in the text.
`\#|...|#`:: 'Hash-pipe' denotes the start of a block comment. The comment ends at the next 'Pipe-hash'.
`'`:: A quote tells Bard not to evaluate the next expression it encounters, but instead to return the expression unchanged.
