= Bard 6: A high-level sketch of Bard 0.6
mikel evins <mikel@evins.net>
:toc:

== Goals of Bard 6

. It's an old-fashioned Lisp, with all the amenities for *programming-as-teaching*.
. The surface language is conceptually simple, with a small number of flexible data structures and a built-in library of generic operations on them.
. It's designed for interactive programming.
. It can build programs for servers, desktop computers, web applications, and mobile devices.
. It can compile to efficient native code without losing interactivity.

== Data

Bard 6 offers the following basic data types:

[cols="1,5",options="header"]
.Bard types
|===
| type name |  description
| `Null` | The type of `nothing`.
| `Boolean` | `true` or `false`; logical operations also treat `nothing` as false.
| `Number` | A number.
| `Text` | A text string.
| `List` | A sequence of values.
| `Map` | A mappings from keys to values.
| `Operation` | An object that can be applied to arguments to compute a result.
| `Structure` | A blueprint for contructing values.
|===

=== Types and structures

Bard *types* are abstract collections of values. *Structures*, on the other hand, are blueprints used for constructing concrete values. A structure is an object that describes in detail how to allocate a chunk of memory to represent a particular kind of value. It also specifies a set of methods that can operate on the values that it creates.

A *type*, on the other hand, is a named input or output role in an operation.

For example, the type of the *function* `length` is

 [List -> Number]

This type signature says that the function `length` takes a single argument of type `List`, and returns a single value of type `Number`. It does not say how `List` or `Number` should be represented; any structure might be a `List` or a `Number`, as long as the necessary functions are *specialized* for it.

== Operations

There are four kinds of Bard operations:

[cols="1,5",options="header"]
.Bard operations
|===
| operation type |  description
| *method* | A *monomorphic* procedure.
| *function* | A *polymoprhic* procedure that, when called, dispatches to a *method* based on computable properties of its arguments.
| *special form* | A built-in operator defined by Bard.
| *macro* | A procedure that rewrites an application expression before evaluating it. Macros are used to define syntax extensions.
|===

== Runtime system

Bard 6 is a virtual machine that executes portable bytecode. It supports compiling *Bard source code*, in the form of *s-expressions*, to a bytecode called "bardo". It also supports compiling bardo to native machine code.

Bard methods may be represented either as portable bytecode or as platform-specific native code. The Bard VM can run programs made up of either, or of a mix of both.
