= bard 0.7

== Literal Constants

`undefined`:: No useful value
`nothing`:: An empty list, map, or stream
`true`:: The Boolean true value
`false`:: The Boolean false value

== Special Forms

[horizontal]
`apply`:: Call a procedure with a list of parameters
`begin`:: Evaluate a sequence of expressions and return the value of the last
`bound?`:: Test whether a *variable* or *slot* has a value
`const`:: Define an *immutable global variable*
`def`:: Define a *mutable global variable*
`define`:: Define one of several global constructs, including classes, functions, and macros
`if`:: Choose which of two expressions to evaluate
`let`:: Define a set of *immutable lexical variables*
`method`:: Create a *monomorphic* procedure
`quote`:: Ask Bard not to evaluate an expression, but instead to return it unchanged
`set!`:: Update the value of a *mutable variable*
`setter`:: Return a procedure that can update a *variable* or *slot*
`unwind-protect`:: Create a control structure that can guarantee that an *exit expression* is evaluated, no matter how control leaves the structure
`values`:: Return zero or more values
`var`:: Define a set of *mutable lexical variables*
`with-exit`:: Create a control structure that defines an *exit procedure* within the structure

== Core Functions

[horizontal]
`initialize`:: A function automatically called by Bard that sets up the initial state of a newly-constructed value
`make`:: A function that allocates a new Bard value


== Built-in Protocols

[horizontal]
`Comparing`:: Operations that compare identity, equivalence, or sort order
`Conditions`:: Values and operations that represent and handle exceptional occurrences
`Control`:: Extended control structures
`Functions`:: Operations on functions and methods
`Lists`:: Creating and operating on ordered sequences of values
`Macro`:: Defining and using *macros*, and several built-in macros
`Map`:: Creating and operating on finite maps from keys to values
`Math`:: Numbers and mathematical operations
`Messaging`:: Communication between local and remote Bard processes
`Names`:: Creating and operating on *names* including *symbols*, *keywords*, and *uris*
`Network`:: Creating and operating on network connections
`Processes`:: Creating and operating on local and remote Bard processes
`Streams`:: Creating and operating on objects that produce or consume sequences of values
`System`:: Operations on the Bard runtime system
`Taps`:: Operations that create streams from procedures and values
`Text`:: Creating and operating on text strings and text characters
`Types`:: Operations on types

